[package]
name = "cookies"
version = "0.1.0"
authors = ["Sean McArthur <sean@seanmonstar.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.1"

[dev-dependencies]
cookie = "0.12"
